export type Service = {
  title: string;
  icon: string;
  intro: string;
  included: string[];
  whyHeading: string;
  whyBody: string;
  problems: string[];
  core: { icon: string; title: string; desc: string }[];
  experts: { icon: string; role: string }[];
  ctaHeading: string;
};

export const serviceData: Record<string, Service> = {
  "ai-strategy": { title: "AI Strategy & Digital Growth Consulting", icon: "insights", intro: "A clear, data-informed roadmap that aligns your goals, market, and technology — so every dollar and hour you invest moves growth forward.", included: ["Growth audit & opportunity map", "Go-to-market strategy", "Funnel & conversion strategy", "Tech stack recommendations", "AI leverage plan"], whyHeading: "Strategy is the difference between busy and growing.", whyBody: "Without a clear plan, teams invest in tactics that do not connect. We start by understanding your business, market, and customers, then design a growth system where website, marketing, content, automation, and reporting reinforce each other. The result is direction you can act on with confidence.", problems: ["No clear growth roadmap or priorities", "Marketing tactics that don't connect to revenue", "Unsure where AI can actually add leverage", "Disconnected tools and fragmented data", "Investment without measurable return", "Decisions made on guesswork, not data"], core: [{ icon: "query_stats", title: "Growth Audit", desc: "A full review of your current digital system and where it leaks." }, { icon: "rocket_launch", title: "Go-To-Market Strategy", desc: "A plan for reaching and converting your ideal customers." }, { icon: "conversion_path", title: "Funnel Strategy", desc: "Mapping the path from first touch to closed revenue." }, { icon: "groups", title: "Persona Research", desc: "Deep clarity on who you serve and what moves them." }, { icon: "lan", title: "Tech Stack Consulting", desc: "The right tools, integrated to work as one engine." }, { icon: "psychology", title: "AI Leverage Plan", desc: "Where automation and AI create real efficiency gains." }], experts: [{ icon: "strategy", role: "Growth Strategist" }, { icon: "query_stats", role: "Market Analyst" }, { icon: "psychology", role: "AI Consultant" }, { icon: "conversion_path", role: "Funnel Specialist" }], ctaHeading: "Ready to Build Your Growth Roadmap?" },
  website: { title: "Website Design & Development", icon: "devices", intro: "Fast, high-converting websites engineered around your buyer's journey — built to turn traffic into qualified pipeline, not just look good.", included: ["UX & conversion-focused design", "Responsive development", "CMS setup & training", "Core Web Vitals optimization", "Analytics & tracking setup"], whyHeading: "Your website is your hardest-working growth asset.", whyBody: "A beautiful site that doesn't convert is a missed opportunity. We design around how your buyers actually decide, build for speed and accessibility, and wire in the tracking you need to keep improving. Every page has a job to do in your growth system.", problems: ["High traffic but low conversions", "Slow load times hurting rankings and trust", "Outdated design that doesn't reflect the brand", "No clear path from visitor to lead", "Hard-to-update content management", "No tracking to know what works"], core: [{ icon: "web", title: "Conversion-First Design", desc: "Layouts built around how buyers actually decide." }, { icon: "code", title: "Responsive Development", desc: "Pixel-perfect across desktop, tablet, and mobile." }, { icon: "article", title: "CMS Build", desc: "WordPress, Webflow, or your platform of choice." }, { icon: "speed", title: "Performance Tuning", desc: "Fast load times and strong Core Web Vitals." }, { icon: "accessibility", title: "Accessibility", desc: "Inclusive, standards-compliant builds." }, { icon: "analytics", title: "Tracking Setup", desc: "Analytics and events wired in from day one." }], experts: [{ icon: "design_services", role: "UX Designer" }, { icon: "code", role: "Frontend Developer" }, { icon: "edit_note", role: "Conversion Copywriter" }, { icon: "speed", role: "Performance Engineer" }], ctaHeading: "Ready for a Website That Converts?" },
  seo: { title: "SEO & AI Search Visibility", icon: "travel_explore", intro: "Be found and chosen across Google and AI search engines through technical SEO, content strategy, and AI search optimization that compounds over time.", included: ["Technical SEO audit & fixes", "Keyword & content strategy", "On-page optimization", "AI search & answer optimization", "Reporting & rank tracking"], whyHeading: "Search is shifting — and visibility compounds.", whyBody: "Buyers now discover answers across traditional search and AI engines. We build durable organic visibility through clean technical foundations, content that earns trust, and optimization for how AI surfaces answers. Unlike ads, the value keeps growing after the work is done.", problems: ["Invisible on search for key terms", "Technical issues blocking crawlers", "Content that doesn't rank or convert", "Losing visibility to AI-generated answers", "No local presence in map results", "No clarity on what drives rankings"], core: [{ icon: "build", title: "Technical SEO", desc: "Site health, speed, and crawlability fixed at the root." }, { icon: "key", title: "Keyword Strategy", desc: "Targeting the terms your buyers actually search." }, { icon: "edit_note", title: "Content Optimization", desc: "Pages built to rank and to convert." }, { icon: "smart_toy", title: "AI Search Optimization", desc: "Structured to surface in AI answers and AEO/GEO." }, { icon: "pin_drop", title: "Local SEO", desc: "Map pack and local visibility for nearby buyers." }, { icon: "monitoring", title: "Rank Reporting", desc: "Clear tracking of visibility and organic growth." }], experts: [{ icon: "travel_explore", role: "SEO Lead" }, { icon: "build", role: "Technical SEO" }, { icon: "edit_note", role: "Content Strategist" }, { icon: "smart_toy", role: "AI Search Specialist" }], ctaHeading: "Ready to Grow Your Search Visibility?" },
  "paid-ads": { title: "Paid Advertising & Performance Marketing", icon: "ads_click", intro: "Profitable, well-tracked campaigns across Google, Meta, LinkedIn, and more — built to scale spend only where it returns.", included: ["Campaign strategy & setup", "Creative & ad copy", "Conversion tracking", "Ongoing optimization", "Transparent performance reporting"], whyHeading: "Paid media should be an investment, not a gamble.", whyBody: "Most ad spend is wasted on poor targeting, weak creative, and broken tracking. We build campaigns on a foundation of clear measurement, test relentlessly, and scale only what proves profitable. You see exactly where every dollar goes and what it returns.", problems: ["Ad spend with unclear returns", "Poor targeting wasting budget", "Weak creative that doesn't convert", "Broken or missing conversion tracking", "Campaigns that don't scale profitably", "No clear reporting on performance"], core: [{ icon: "ads_click", title: "Google Ads", desc: "Search, Display, Performance Max, and YouTube." }, { icon: "thumb_up", title: "Meta Ads", desc: "Facebook and Instagram demand generation." }, { icon: "work", title: "LinkedIn Ads", desc: "B2B targeting for high-value pipeline." }, { icon: "brush", title: "Ad Creative", desc: "Scroll-stopping creative and copy that converts." }, { icon: "track_changes", title: "Conversion Tracking", desc: "Accurate measurement down to revenue." }, { icon: "tune", title: "Optimization", desc: "Continuous testing to lower cost per result." }], experts: [{ icon: "ads_click", role: "Paid Media Lead" }, { icon: "brush", role: "Ad Creative Designer" }, { icon: "track_changes", role: "Analytics Specialist" }, { icon: "edit_note", role: "Direct-Response Copywriter" }], ctaHeading: "Ready to Make Paid Ads Profitable?" },
  social: { title: "Social Media Marketing & Content Creation", icon: "share", intro: "Consistent, on-brand content that builds audience, authority, and demand across the platforms where your customers spend their time.", included: ["Content strategy & calendar", "Creative & video production", "Community management", "Platform growth tactics", "Performance reporting"], whyHeading: "Attention is earned with consistency and craft.", whyBody: "Sporadic posting doesn't build an audience. We develop a content strategy rooted in your brand and goals, produce content people actually want to engage with, and stay consistent so your presence compounds into real authority and demand.", problems: ["Inconsistent or off-brand posting", "Low engagement and slow growth", "No content strategy or calendar", "Struggling to produce enough content", "Unclear which content drives results", "No time to manage community"], core: [{ icon: "calendar_month", title: "Content Strategy", desc: "A clear plan and calendar tied to your goals." }, { icon: "videocam", title: "Video & Creative", desc: "Short-form video, graphics, and carousels." }, { icon: "forum", title: "Community Management", desc: "Engaging your audience and growing reach." }, { icon: "trending_up", title: "Growth Tactics", desc: "Platform-native tactics that expand reach." }, { icon: "auto_awesome", title: "On-Brand Content", desc: "Every post reinforces your identity." }, { icon: "monitoring", title: "Reporting", desc: "Clear view of what content performs." }], experts: [{ icon: "share", role: "Social Strategist" }, { icon: "videocam", role: "Content Creator" }, { icon: "brush", role: "Designer" }, { icon: "forum", role: "Community Manager" }], ctaHeading: "Ready to Build Your Social Presence?" },
  content: { title: "Content Marketing & Copywriting", icon: "edit_note", intro: "Words that rank, resonate, and move buyers toward a decision — from blog content and thought leadership to high-converting sales copy.", included: ["Content strategy", "SEO blog & articles", "Website & sales copy", "Email sequences", "Case studies & whitepapers"], whyHeading: "Great content earns attention and trust.", whyBody: "Content is how you demonstrate expertise, rank in search, and guide buyers toward a decision. We develop a strategy aligned to your funnel, then produce content that's genuinely useful and persuasive — not filler. Every piece works toward visibility and conversion.", problems: ["Content that doesn't rank or convert", "No consistent publishing rhythm", "Weak or unclear messaging", "Thin content that doesn't build authority", "No content tied to the buyer journey", "Copy that doesn't drive action"], core: [{ icon: "map", title: "Content Strategy", desc: "A roadmap mapped to your funnel and SEO goals." }, { icon: "article", title: "SEO Articles", desc: "Blog content built to rank and educate." }, { icon: "draw", title: "Sales Copy", desc: "Website and landing page copy that converts." }, { icon: "mail", title: "Email Copywriting", desc: "Sequences that nurture and close." }, { icon: "lightbulb", title: "Thought Leadership", desc: "Authority content that builds credibility." }, { icon: "description", title: "Case Studies", desc: "Proof-driven assets that win deals." }], experts: [{ icon: "edit_note", role: "Content Strategist" }, { icon: "draw", role: "Copywriter" }, { icon: "travel_explore", role: "SEO Writer" }, { icon: "description", role: "Editor" }], ctaHeading: "Ready to Make Content a Growth Engine?" },
  branding: { title: "Branding & Creative Services", icon: "palette", intro: "A distinct, cohesive identity that earns trust and stands apart — from logo and visual system to pitch decks and brand kits.", included: ["Brand strategy & positioning", "Logo & visual identity", "Brand guidelines", "Pitch deck design", "Social media brand kits"], whyHeading: "A strong brand makes every other effort work harder.", whyBody: "Brand is what makes you memorable and trusted before a word is read. We define your positioning, then build a visual identity and system that's consistent everywhere your business shows up. The result is recognition, credibility, and a premium perception.", problems: ["Inconsistent or dated visual identity", "Brand that blends in with competitors", "No clear positioning or messaging", "Disjointed assets across channels", "Low trust at first impression", "No brand guidelines to scale with"], core: [{ icon: "auto_awesome", title: "Brand Strategy", desc: "Positioning that sets you apart." }, { icon: "brush", title: "Logo Design", desc: "A distinctive, versatile mark." }, { icon: "palette", title: "Visual Identity", desc: "Color, type, and a complete system." }, { icon: "menu_book", title: "Brand Guidelines", desc: "Rules that keep everything consistent." }, { icon: "slideshow", title: "Pitch Decks", desc: "Investor and sales decks that land." }, { icon: "collections", title: "Brand Kits", desc: "Templates for social and marketing." }], experts: [{ icon: "auto_awesome", role: "Brand Strategist" }, { icon: "brush", role: "Brand Designer" }, { icon: "palette", role: "Art Director" }, { icon: "slideshow", role: "Presentation Designer" }], ctaHeading: "Ready to Build a Brand That Stands Out?" },
  automation: { title: "AI Automation & AI Solutions", icon: "smart_toy", intro: "Automate follow-up, lead qualification, and repetitive workflows with AI-driven systems that save time and never let an opportunity slip.", included: ["Workflow automation", "AI chatbots & assistants", "CRM automation", "AI lead qualification", "Automated reporting"], whyHeading: "Automation turns manual work into compounding leverage.", whyBody: "Every hour spent on repetitive tasks is an hour not spent growing. We map your workflows, then build AI-enabled systems that handle follow-up, qualification, routing, and reporting automatically. Your team focuses on high-value work while the system handles the rest — reliably and at scale.", problems: ["Slow, manual lead follow-up", "Leads slipping through the cracks", "Repetitive tasks eating team time", "Disconnected tools requiring manual work", "No instant response to inquiries", "Reporting built by hand each week"], core: [{ icon: "chat", title: "AI Chatbots", desc: "Website and WhatsApp bots that qualify and route." }, { icon: "sync_alt", title: "CRM Automation", desc: "Automatic lead capture, routing, and nurture." }, { icon: "filter_alt", title: "Lead Qualification", desc: "AI scoring so sales focuses on the best leads." }, { icon: "outgoing_mail", title: "Email Automation", desc: "Triggered sequences that follow up instantly." }, { icon: "account_tree", title: "Workflow Automation", desc: "Connect your tools into one seamless flow." }, { icon: "monitoring", title: "Automated Reporting", desc: "Dashboards that build themselves." }], experts: [{ icon: "smart_toy", role: "AI Engineer" }, { icon: "account_tree", role: "Automation Specialist" }, { icon: "sync_alt", role: "CRM Consultant" }, { icon: "integration_instructions", role: "Integrations Developer" }], ctaHeading: "Ready to Automate Your Growth System?" },
  software: { title: "Mobile App & Software Development", icon: "code", intro: "Custom apps, SaaS MVPs, dashboards, and portals built to scale — engineered for performance, usability, and real business outcomes.", included: ["Product discovery & scoping", "UI/UX design", "Web & mobile development", "SaaS MVP build", "Dashboards & portals"], whyHeading: "Software should solve real problems, fast.", whyBody: "Whether you're launching a SaaS product or building internal tools, the goal is the same: something people actually use that drives outcomes. We scope tightly, design for clarity, and build with scale in mind — so you ship faster and grow without rework.", problems: ["Manual processes that need a custom tool", "A product idea with no clear path to MVP", "Spreadsheets where you need a real system", "No dashboard to see what matters", "Clunky internal tools slowing the team", "Tech debt blocking growth"], core: [{ icon: "explore", title: "Product Discovery", desc: "Scoping the right thing to build first." }, { icon: "design_services", title: "UI/UX Design", desc: "Intuitive interfaces people enjoy using." }, { icon: "rocket", title: "SaaS MVP", desc: "Launch-ready products to validate fast." }, { icon: "smartphone", title: "Mobile Apps", desc: "Native-quality iOS and Android experiences." }, { icon: "space_dashboard", title: "Admin Dashboards", desc: "Control panels for your operations." }, { icon: "account_circle", title: "Customer Portals", desc: "Self-serve experiences for your users." }], experts: [{ icon: "code", role: "Full-Stack Developer" }, { icon: "design_services", role: "Product Designer" }, { icon: "explore", role: "Product Manager" }, { icon: "verified", role: "QA Engineer" }], ctaHeading: "Ready to Build Your Product?" },
  ecommerce: { title: "Ecommerce & Marketplace Growth", icon: "shopping_cart", intro: "Store setup and optimization that lifts revenue per visitor — across Shopify, WooCommerce, and major marketplaces.", included: ["Store setup & migration", "Product page optimization", "Conversion rate optimization", "Marketplace consulting", "Ecommerce analytics"], whyHeading: "Small conversion gains compound into big revenue.", whyBody: "In ecommerce, every percentage point of conversion and average order value matters. We build and optimize stores around how shoppers buy, fix the friction that loses sales, and expand into marketplaces strategically — so each visitor is worth more.", problems: ["Low conversion on product pages", "High cart abandonment", "Poor mobile shopping experience", "No strategy for marketplaces", "Slow store performance", "No clarity on what drives sales"], core: [{ icon: "add_business", title: "Store Setup", desc: "Shopify and WooCommerce builds and migrations." }, { icon: "inventory_2", title: "Product Pages", desc: "Optimized pages that convert browsers to buyers." }, { icon: "trending_up", title: "CRO", desc: "Testing to lift conversion and order value." }, { icon: "store", title: "Marketplaces", desc: "Strategy for Amazon and other channels." }, { icon: "speed", title: "Performance", desc: "Fast stores that don't lose sales to lag." }, { icon: "monitoring", title: "Ecom Analytics", desc: "Tracking the metrics that drive revenue." }], experts: [{ icon: "shopping_cart", role: "Ecommerce Strategist" }, { icon: "code", role: "Shopify Developer" }, { icon: "trending_up", role: "CRO Specialist" }, { icon: "brush", role: "Product Page Designer" }], ctaHeading: "Ready to Grow Your Store Revenue?" },
  analytics: { title: "Data, Analytics & Reporting", icon: "monitoring", intro: "Tracking and dashboards that turn raw data into clear decisions — so you always know what's working and where to invest next.", included: ["GA4 & GTM setup", "Conversion & funnel tracking", "Looker Studio dashboards", "CRM & revenue reporting", "Ongoing insights"], whyHeading: "You can't improve what you can't see.", whyBody: "Most businesses are flying blind or drowning in numbers that don't mean anything. We set up clean, accurate tracking and build dashboards that surface the few metrics that matter — turning data into decisions you can act on with confidence.", problems: ["No clear view of what's working", "Inaccurate or missing tracking", "Data scattered across tools", "Reports that don't drive decisions", "No funnel or conversion visibility", "Hours wasted building reports by hand"], core: [{ icon: "analytics", title: "GA4 Setup", desc: "Accurate analytics configured correctly." }, { icon: "sell", title: "Tag Manager", desc: "Event tracking without developer bottlenecks." }, { icon: "dashboard", title: "Looker Dashboards", desc: "Live dashboards for the metrics that matter." }, { icon: "filter_list", title: "Funnel Tracking", desc: "See exactly where you lose and win." }, { icon: "table_chart", title: "CRM Reporting", desc: "Pipeline and revenue visibility." }, { icon: "lightbulb", title: "Insights", desc: "Analysis that points to the next move." }], experts: [{ icon: "monitoring", role: "Analytics Lead" }, { icon: "sell", role: "Tracking Specialist" }, { icon: "dashboard", role: "Data Visualization" }, { icon: "query_stats", role: "Data Analyst" }], ctaHeading: "Ready to See Your Growth Clearly?" },
  local: { title: "Online Reputation & Local Business Growth", icon: "location_on", intro: "More reviews, stronger local visibility, and a Google presence that turns nearby searches into customers walking through your door.", included: ["Google Business Profile optimization", "Review generation system", "Map pack & local SEO", "Reputation management", "Local lead generation"], whyHeading: "Local buyers decide based on what they see first.", whyBody: "When someone searches nearby, your reviews, profile, and map ranking decide whether they choose you or a competitor. We optimize your local presence, build a steady flow of authentic reviews, and protect your reputation — so you win the moments that matter most.", problems: ["Low visibility in local map results", "Few or outdated customer reviews", "Incomplete Google Business Profile", "Negative reviews hurting reputation", "Losing local customers to competitors", "No system to generate referrals"], core: [{ icon: "business", title: "Google Profile", desc: "Fully optimized Business Profile." }, { icon: "reviews", title: "Review Generation", desc: "A system for steady, authentic reviews." }, { icon: "map", title: "Map Pack SEO", desc: "Ranking in the local 3-pack." }, { icon: "verified", title: "Reputation Mgmt", desc: "Monitoring and protecting your image." }, { icon: "pin_drop", title: "Local Lead Gen", desc: "Turning local searches into customers." }, { icon: "star", title: "Review Strategy", desc: "Turning happy customers into advocates." }], experts: [{ icon: "location_on", role: "Local SEO Specialist" }, { icon: "reviews", role: "Reputation Manager" }, { icon: "business", role: "GBP Specialist" }, { icon: "pin_drop", role: "Local Lead Strategist" }], ctaHeading: "Ready to Win Your Local Market?" },
  retainers: { title: "Website, Marketing & AI Maintenance Retainers", icon: "autorenew", intro: "Ongoing partnership and continuous improvement — keeping your website, marketing, automation, and analytics performing month after month.", included: ["Website care & updates", "Ongoing SEO & content", "Ads management", "Automation maintenance", "Monthly reporting"], whyHeading: "Growth systems need ongoing care to keep compounding.", whyBody: "Launching is just the start. Search, ads, content, and automation all need continuous attention to keep improving. Our retainers give you a dedicated team that maintains, optimizes, and reports on your systems every month — so performance keeps climbing instead of decaying.", problems: ["Performance decaying after launch", "No time to maintain systems in-house", "Inconsistent marketing output", "Tools and automations breaking silently", "No ongoing optimization", "Unclear monthly reporting"], core: [{ icon: "health_and_safety", title: "Website Care", desc: "Updates, security, and improvements." }, { icon: "travel_explore", title: "SEO Retainer", desc: "Continuous content and ranking growth." }, { icon: "ads_click", title: "Ads Management", desc: "Always-on optimization of paid campaigns." }, { icon: "smart_toy", title: "Automation Care", desc: "Keeping AI workflows running smoothly." }, { icon: "share", title: "Social & Content", desc: "A steady stream of on-brand content." }, { icon: "monitoring", title: "Monthly Reporting", desc: "Clear updates on progress and results." }], experts: [{ icon: "support_agent", role: "Account Manager" }, { icon: "travel_explore", role: "SEO Specialist" }, { icon: "ads_click", role: "Media Buyer" }, { icon: "smart_toy", role: "Automation Engineer" }], ctaHeading: "Ready for a Long-Term Growth Partner?" },
};

export const allServiceLinks = [
  { slug: "ai-strategy", title: "AI Strategy & Consulting", icon: "insights" },
  { slug: "website", title: "Website Design & Dev", icon: "devices" },
  { slug: "seo", title: "SEO & AI Search", icon: "travel_explore" },
  { slug: "paid-ads", title: "Paid Advertising", icon: "ads_click" },
  { slug: "social", title: "Social & Content", icon: "share" },
  { slug: "content", title: "Content & Copywriting", icon: "edit_note" },
  { slug: "branding", title: "Branding & Creative", icon: "palette" },
  { slug: "automation", title: "AI Automation", icon: "smart_toy" },
  { slug: "software", title: "App & Software Dev", icon: "code" },
  { slug: "ecommerce", title: "Ecommerce Growth", icon: "shopping_cart" },
  { slug: "analytics", title: "Data & Analytics", icon: "monitoring" },
  { slug: "local", title: "Reputation & Local", icon: "location_on" },
];

export const deliveryApproach = [
  { num: "01", title: "Discovery", desc: "We learn your goals, audience, and current state." },
  { num: "02", title: "Plan", desc: "We define scope, priorities, and a clear roadmap." },
  { num: "03", title: "Build & Execute", desc: "Our specialists deliver the work in tight cycles." },
  { num: "04", title: "Optimize & Report", desc: "We measure, improve, and report transparently." },
];
